import {
  mdiCartPlus,
  mdiAccount,
  mdiEmail,
  mdiAccountGroup,
  mdiMinusCircleOutline,
  mdiPlus,
  mdiClose,
  mdiCheck,
  mdiNote,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronDown,
  mdiChevronUp,
  mdiMinus,
  mdiCalendarRange,
  mdiClockOutline,
  mdiStar,
  mdiMenu,
  mdiTranslate,
  mdiPhone,
  mdiBellOutline,
  mdiTag,
  mdiInformationOutline,
  mdiCog,
  mdiFileDocumentOutline,
  mdiPlaylistCheck,
  mdiCalendarText,
  mdiCurrencyEur,
  mdiMagnify,
  mdiSortAlphabeticalVariant,
  mdiArrowUp,
  mdiArrowDown,
  mdiFerry
} from '@mdi/js'

export const ICONS = {
  cart: mdiCartPlus,
  person: mdiAccount,
  email: mdiEmail,
  people: mdiAccountGroup,
  addCart: mdiCartPlus,
  removeItem: mdiMinusCircleOutline,
  add: mdiPlus,
  close: mdiClose,
  open: mdiPlus,
  done: mdiCheck,
  accept: mdiCheck,
  note: mdiNote,
  arrowLeft: mdiChevronLeft,
  arrowRight: mdiChevronRight,
  arrowDown: mdiChevronDown,
  arrowUp: mdiChevronUp,
  remove: mdiMinus,
  dateRange: mdiCalendarRange,
  accessTime: mdiClockOutline,
  star: mdiStar,
  menu: mdiMenu,
  translate: mdiTranslate,
  phone: mdiPhone,
  notify: mdiBellOutline,
  discount: mdiTag,
  info: mdiInformationOutline,
  settings: mdiCog,
  description: mdiFileDocumentOutline,
  addCheck: mdiPlaylistCheck,
  eventNote: mdiCalendarText,
  tag: mdiTag,
  euro: mdiCurrencyEur,
  search: mdiMagnify,
  alpha: mdiSortAlphabeticalVariant,
  upward: mdiArrowUp,
  downward: mdiArrowDown,
  boat: mdiFerry
}
